### ISSUE TITLE
Feature Request: Rotation offset.

### ISSUE THREAD

**Issue by asdexter** [Varriount/fvtt-autorotate#14]
Some art packs have top down tokens at diagonals instead of facing down. In these cases, it would be nice to have a rotation offset angle that we could enter so the module would work correctly in those cases.

**Comment by CyleJS** [comment]
Seconded. Please please please implement this. The rotation offset in Foundry default works for initial token placement, but gets reset as soon as the token moves for the first time.

**Comment by KammaKhazi** [comment]
would love to see this feature also. A lot of horses are on a diagonal so hard to implement in conjunction with foundry vtt mount up currently.

**Comment by asdexter** [comment]
Hey I had locked my updates until recently I'm updating everything and saw that this feature was added. Thank you so much!
