### ISSUE TITLE
FVTT V9 - Depreciation Warning

### ISSUE THREAD

**Issue by AurelTristen** [Varriount/fvtt-autorotate#16]
Hello, and thanks for this small but vital module.
Moving a token gives this warning every time:
`Deprecated since V9, will be removed in V10. Use game.keyboard.downKeys.has instead.`

Everything still works! But I thought I'd report this before V10 breaks things.

**Comment by thatlonelybugbear** [comment]
I think this would help https://github.com/Varriount/fvtt-autorotate/pull/15

**Comment by epsilon7430** [comment]
Confirming I also see this warning appear in console log every time a token is moved with Auto-Rotate module enabled. :-)
