### ISSUE TITLE
Token rotation checkbox is missing on V9

### ISSUE THREAD

**Issue by chklein1** [Varriount/fvtt-autorotate#17]
On Foundry V1 build 238 + DnD5e 1.5.6 + Auto-Rotate 1.2.6, I'm no longer seeing the per-token checkbox to enable/disable auto-rotation. Note that existing tokens (both those that auto-rotate and those that don't) are still behaving correctly, and the Lock checkbox does override behavior for tokens that previously had auto-rotate enabled. I assume the change was caused by V9 changes to the token configuration UI, which no longer contains a "Position" tab.
 
![image](https://user-images.githubusercontent.com/85462739/148023122-0b0b2f47-84c2-4859-bb89-a6007db45c57.png)

**Comment by Clashsoft** [comment]
Having the same problem. Please fix immediately, it makes this module almost impossible to use. The only workaround is to copy existing tokens that are already configured to auto-rotate. That is obviously not possible when installing the module for the first time or creating a new world.

**Comment by Varriount** [comment]
@Clashsoft @chklein1 This should be fixed now. Sorry for the delay!
