### ISSUE TITLE
Update to v10

### ISSUE THREAD

**Issue by CaosFR** [Varriount/fvtt-autorotate#21]
Hi,

Thanks for your module and work. Does it possible to update the module for the v10 ?

In the module.json I can see : 
```
  "minimumCoreVersion": "0.8.5",
  "compatibleCoreVersion": "9",
```

Happy dev

**Comment by weepingminotaur** [comment]
Would love to see this module updated for v10!

**Comment by aedgaruk** [comment]
Arguably one of the most essential QoL mods for those of us who use top-down tokens ... please update to v10 :)

**Comment by jorgecomas** [comment]
Definitely, an update for this module would be a gift! 
Honestly, autorotate should be a core feature by now.
Thanks for your work!

**Comment by skellitor301** [comment]
The module does still work in v10, it just needs to have the version number changed

**Comment by GambetTV** [comment]
It works, but very poorly with v10's new smooth animated rotation effects. If you drag a left-facing token right 20 squares, the rotation animation will begin at the start of the token movement and end at the end of it. There's nothing like seeing a token take 6 seconds to rotate 180 degrees, let me tell you, but it should definitely be smoothed out.

**Comment by skellitor301** [comment]
Thing is that is an issue only when the token is dragged from one tile to another. If you use arrow keys, WASD, or the numpad it actually looks great. Maybe have a system in place to not have the smooth animation when the token is dragged by mouse, and leave the animaton when moved by key.

**Comment by Wade0004** [comment]
I get a few console errors since the update also:
"setup.js:145 [autorotate] The module "autorotate" is using the old flat core compatibility fields which are deprecated in favor of the new "compatibility" object"
"setup.js:145 [autorotate] The module "autorotate" is using "author" which is deprecated in favor of "authors""
