### ISSUE TITLE
Compatibility Error - "setup.js:145 [autorotate] The module "autorotate" is using "author" which is deprecated in favor of "authors""

### ISSUE THREAD

**Issue by MagicOriole** [Varriount/fvtt-autorotate#27]
Minor error, I just hate yellow flags. LOVE this mod though!

**Comment by MagicOriole** [comment]
![image](https://user-images.githubusercontent.com/96490347/207703588-77ae3193-22f4-4221-a628-047bf0d84020.png)

**Comment by MagicOriole** [comment]
Bump! I know you're a busy and I appreciate you! Thanks!

**Comment by Varriount** [comment]
@MagicOriole I believe I've fixed this with the latest release - can you test and confirm?

**Comment by MagicOriole** [comment]
Confirmed! Thanks so much Varriount!
