### ISSUE TITLE
Doesn't work with Foundry v11

### ISSUE THREAD

**Issue by sesopenko** [Varriount/fvtt-autorotate#29]
Auto rotate stops working with Foundry v11.  The tokens no longer rotate to face their targets.

**Comment by Varriount** [comment]
Huh, do they still rotate when they move?

**Comment by Varriount** [comment]
@sesopenko So, I've tested on my Foundry instance, and Autorotate appears to work. Are you receiving any specific errors in the console? What are your settings set to?

**Comment by sesopenko** [comment]
I've determined that the instance had drive data corruption, it was
experiencing all sorts of issues due to corrupted files, including the os
system. I exported the characters, installed a fresh os and foundry, then
added the plugin and the problems no longer occur. This can be closed.
