### ISSUE TITLE
[Bug] no valid manifest file

### ISSUE THREAD

**Issue by PaulWRoberts** [Varriount/fvtt-autorotate#7]
When checking for updates you get the error message
"The request to https://github.com/Varriount/fvtt-autorotate/releases/download/TAG_VERSION/module.json did not provide a valid manifest file."

I cannot say for sure, but the inclusion of the text "TAG_VERSION" is pretty sus.

**Comment by Varriount** [comment]
Ok, this *should* be fixed now. All you should have to do is update the module - I put a dummy release in place with the name of TAG_VERSION, which should direct Foundry to the latest release's manifest (1.1.2).
