### ISSUE TITLE
0.8.x Compatibility

### ISSUE THREAD

**Issue by rmasoni** [Varriount/fvtt-autorotate#9]
The module doesn't seem to be working properly on 0.8.x. Any plans to update?

**Comment by Varriount** [comment]
Yep. Working on it right now.

**Comment by Varriount** [comment]
Ok, I've uploaded a new package - let me know if it installs for you. If it does, then feel free to close the issue.

**Comment by rmasoni** [comment]
It does install, and works perfectly! Thank you!
